---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-object-storage
  namespace: minio
spec:
  encryptedData:
    thanos.yaml: AgBWPM005hjMZTHVy8iqyLTmXlyE9wrcUWqj2dtMQjHHyHvZIuEqnJw2U0TPz5E4SdtqCfPGzEWiogLizN9JSRtWrBFvdKe+HNsAvJ4U3Ae31GDcbN7pj4xKE1jKAF460385ErAUKuqzQeCl0TbcDOzCtcA+ZLcaiX/1ZqH4UvEh+FYJ2KFOzdu0VwSnWBZPr5pAYP4g2o2LFF2OkdlqijOLeJcMZZORiQwGTTZclfbFiUZe6YPYUNvHaCZ3vS+QaZEPVDtewHzom5mqsPXd7ythBrWIwUu3o5QwaEWsVARGvX0Aegju11vXelXT3a1ViydeXFKJLVdO4SWXgvx2P2Mf65Yyqoseo+v7HvCsyMAkWy+Rd2dtbfXpUSBKHEgGfD5IH5IFVOkoqouN80+9CY8J0wfBi6tIYysJ8wDgEu8e1m3mYVpT8tpAXqlD2o1m+V9U5ZA1SQlHk3sqDA5lxCsSRMpWIuiu1pxms4AZob9z6kKJmbe5jPXA0EDUJN28VK8iMqMZpgdlrhGjlthhgBowZd8+FNpgMjN5ZsCJz/kBbB03fB/4E0FDtgleIyAEOHyircuv6im++RpebfG9gk+VnK9pj4W6moOAfvkCd1hWGjzoqZ5e1TZfKwZ6v7KsDCNvoPfYYvLdpSHlbGUkyg4ZVt2NWsBLRcFA4jl6JNym7JL+nDyk2zDKIpvkLq2wfqx4kEdKq854L7Ryg0Dd1/t43KunMYP9M0I4XMhA/NitPeRY4cLER8DDaqzHpAfosrxfDjUXOe8azFmRCmRW5u56cMIStuiTKEelwuRvkZDeNgEA5Vojr/GAJluXmJRHoRbEPkkPHcLmz5a89UP/36MqRIBxl/B9Eqd9zorfMOKGNNC13uGYYPuvGcxOhkr/WROEGLteQ/zjCMPCmhEzQakx0kxpCgg+mdpqkOKeMvugo4IjLpqz0JxLHRmXwR8kaT3/qj03VkhAPZYOdH+HJ5Y3gHNLnf98NtA=
  template:
    metadata:
      name: thanos-object-storage
      namespace: minio
