apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: openshift-gitops
spec:
  project: platform-services
  source:
    repoURL: https://github.com/atwin140/ahead-dastor.git
    targetRevision: sandbox
    path: components/sealed-secrets/overlays/dastor
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  # Manual sync: automatic sync and automatic pruning are not enabled.
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
