apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patch-minio-pvc.yaml
  target:
    version: v1
    kind: PersistentVolumeClaim
    name: minio-data
