apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  cluster.name: dastor
  cluster.role: management

resources:
- ../../base
- certmanager-config.yaml
- clusterissuer-letsencrypt-prod.yaml
- certificate-wildcard.yaml
- patch-ingress-tls.yaml
